// Static, dependency-free viewer for the report generated by `ai-metrics report build`.
// Served as-is (no bundling) from dist/report-ui.

const config = window.__AI_METRICS_CONFIG__ || {
  markdownRendering: false,
  showPromptBody: true,
  showResponseBody: true,
};

const statusEl = document.getElementById('status');
const metaEl = document.getElementById('report-meta');
const views = {
  overview: document.getElementById('view-overview'),
  prompts: document.getElementById('view-prompts'),
  commits: document.getElementById('view-commits'),
  'provider-model': document.getElementById('view-provider-model'),
  'agent-skill': document.getElementById('view-agent-skill'),
};

document.getElementById('tabs').addEventListener('click', (event) => {
  const button = event.target.closest('.tab');
  if (!button) {
    return;
  }
  for (const tab of document.querySelectorAll('.tab')) {
    tab.classList.toggle('active', tab === button);
  }
  for (const [name, el] of Object.entries(views)) {
    el.hidden = name !== button.dataset.view;
  }
});

document.getElementById('app').addEventListener('click', (event) => {
  const button = event.target.closest('.toggle-body');
  if (!button) {
    return;
  }
  const full = document.getElementById(button.dataset.target);
  const collapsible = button.closest('.collapsible');
  const preview = collapsible.querySelector('.preview');
  const expanding = full.hidden;
  full.hidden = !expanding;
  preview.hidden = expanding;
  button.textContent = expanding ? 'Show less' : 'Show more';
});

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Minimal, dependency-free markdown: fenced/inline code, bold, italic, links, headings, line breaks. */
function renderMarkdown(source) {
  const escaped = escapeHtml(source);
  const withCodeBlocks = escaped.replace(/```([\s\S]*?)```/g, (_, code) => `<pre><code>${code}</code></pre>`);
  const withInlineCode = withCodeBlocks.replace(/`([^`]+)`/g, '<code>$1</code>');
  const withLinks = withInlineCode.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank" rel="noopener">$1</a>');
  const withBold = withLinks.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
  const withItalic = withBold.replace(/(?<!\*)\*([^*]+)\*(?!\*)/g, '<em>$1</em>');
  const withHeadings = withItalic.replace(/^(#{1,3})\s+(.*)$/gm, (_, hashes, text) => `<h${hashes.length}>${text}</h${hashes.length}>`);
  return withHeadings.replace(/\n/g, '<br/>');
}

function renderBody(text) {
  return config.markdownRendering
    ? `<div class="body-text markdown">${renderMarkdown(text)}</div>`
    : `<div class="body-text">${escapeHtml(text)}</div>`;
}

let collapsibleId = 0;
function collapsibleBody(text) {
  if (text.length <= 200) {
    return renderBody(text);
  }
  const id = `body-${++collapsibleId}`;
  const previewText = `${text.slice(0, 200)}…`;
  return `
    <div class="collapsible">
      <div class="preview body-text">${escapeHtml(previewText)}</div>
      <button type="button" class="toggle-body" data-target="${id}">Show more</button>
      <div class="full" id="${id}" hidden>${renderBody(text)}</div>
    </div>
  `;
}

function renderPromptBody(promptBody) {
  if (promptBody === null) {
    return config.showPromptBody
      ? '<p class="redacted">(prompt body not available)</p>'
      : '<p class="redacted">(prompt body hidden — showPromptBody is disabled)</p>';
  }
  return collapsibleBody(promptBody);
}

function renderResponseBody(responseBody) {
  if (responseBody === null) {
    return config.showResponseBody
      ? '<p class="redacted">(response body not available)</p>'
      : '<p class="redacted">(response body hidden — showResponseBody is disabled)</p>';
  }
  return collapsibleBody(responseBody);
}

function formatTokens(value) {
  return value === null ? '—' : value.toLocaleString();
}

function formatNumber(value) {
  return value === null ? '—' : String(Math.round(value * 100) / 100);
}

function formatPercent(value) {
  return value === null ? '—' : `${(value * 100).toFixed(1)}%`;
}

function emptyRow(colspan) {
  return `<tr><td colspan="${colspan}" class="muted">No data</td></tr>`;
}

function statusBadgeClass(status) {
  if (status === 'success') return 'success';
  if (status === 'error') return 'error';
  return '';
}

function breakdownRows(breakdown) {
  return Object.entries(breakdown)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(
      ([key, m]) =>
        `<tr><td>${escapeHtml(key)}</td><td>${m.totalSessions}</td><td>${m.totalActions}</td><td>${formatTokens(m.totalTokens)}</td><td>${formatPercent(m.failedActionRate)}</td></tr>`,
    )
    .join('');
}

function renderOverview(summary) {
  const m = summary.overall;
  const cards = [
    ['Sessions', m.totalSessions],
    ['Actions', m.totalActions],
    ['Total tokens', formatTokens(m.totalTokens)],
    ['Input tokens', formatTokens(m.inputTokens)],
    ['Output tokens', formatTokens(m.outputTokens)],
    ['Cache read tokens', formatTokens(m.cacheReadTokens)],
    ['Cache write tokens', formatTokens(m.cacheWriteTokens)],
    ['Token source', m.tokenSource],
    ['Tokens / session', formatNumber(m.totalTokensPerSession)],
    ['Tokens / commit', formatNumber(m.totalTokensPerCommit)],
    ['Cache rate / session', formatPercent(m.cacheRatePerSession)],
    ['Sessions / commit', formatNumber(m.sessionsPerCommit)],
    ['Actions / session', formatNumber(m.actionsPerSession)],
    ['Failed action rate', formatPercent(m.failedActionRate)],
    ['Uncommitted sessions', m.uncommittedSessions],
  ];

  const statCards = cards
    .map(([label, value]) => `<div class="stat-card"><div class="label">${label}</div><div class="value">${value}</div></div>`)
    .join('');

  const dateRows = Object.entries(summary.byDate)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(
      ([date, metrics]) =>
        `<tr><td>${date}</td><td>${metrics.totalSessions}</td><td>${metrics.totalActions}</td><td>${formatTokens(metrics.totalTokens)}</td></tr>`,
    )
    .join('');

  views.overview.innerHTML = `
    <div class="stat-grid">${statCards}</div>
    <table>
      <caption>By date</caption>
      <thead><tr><th>Date</th><th>Sessions</th><th>Actions</th><th>Total tokens</th></tr></thead>
      <tbody>${dateRows || emptyRow(4)}</tbody>
    </table>
  `;
}

function renderPrompts(sessions) {
  const withPrompts = sessions.filter((session) => session.promptCount > 0);
  if (withPrompts.length === 0) {
    views.prompts.innerHTML = '<p class="muted">No prompts recorded yet.</p>';
    return;
  }

  views.prompts.innerHTML = withPrompts
    .map(
      (session) => `
        <article class="session-card">
          <h3>${escapeHtml(session.sessionId)}</h3>
          <div class="meta">${escapeHtml(session.userSlug)} · ${session.date} · ${session.provider}${
            session.modelRaw ? ` · ${escapeHtml(session.modelRaw)}` : ''
          } · ${session.promptCount} prompt(s)</div>
          ${session.prompts
            .map(
              (prompt) => `
                <div class="body-block">
                  <div class="timestamp">${prompt.timestamp}</div>
                  ${renderPromptBody(prompt.promptBody)}
                </div>
              `,
            )
            .join('')}
        </article>
      `,
    )
    .join('');
}

function renderCommits(summary) {
  const rows = Object.entries(summary.byCommit)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([commit, m]) => {
      const label = commit === 'Uncommitted' ? '<span class="badge uncommitted">Uncommitted</span>' : `<code>${escapeHtml(commit.slice(0, 10))}</code>`;
      return `<tr><td>${label}</td><td>${m.totalSessions}</td><td>${m.totalActions}</td><td>${formatTokens(m.totalTokens)}</td><td>${formatNumber(m.sessionsPerCommit)}</td><td>${formatNumber(m.totalTokensPerCommit)}</td><td>${formatPercent(m.failedActionRate)}</td></tr>`;
    })
    .join('');

  views.commits.innerHTML = `
    <table>
      <caption>By commit</caption>
      <thead><tr><th>Commit</th><th>Sessions</th><th>Actions</th><th>Total tokens</th><th>Sessions/commit</th><th>Tokens/commit</th><th>Failed rate</th></tr></thead>
      <tbody>${rows || emptyRow(7)}</tbody>
    </table>
  `;
}

// Fixed comparison set so claude-code/copilot are visible even with zero sessions, and any
// unrecognized provider still shows up under "unknown" rather than being silently dropped.
const KNOWN_PROVIDERS = ['claude-code', 'copilot', 'unknown'];

function emptyMainMetrics() {
  return {
    totalSessions: 0,
    totalActions: 0,
    inputTokens: null,
    outputTokens: null,
    cacheReadTokens: null,
    totalTokens: null,
    totalTokensPerSession: null,
    totalTokensPerCommit: null,
    failedActionRate: null,
  };
}

function tokenBreakdownRow(key, m) {
  return `<tr><td>${escapeHtml(key)}</td><td>${m.totalSessions}</td><td>${m.totalActions}</td><td>${formatTokens(m.inputTokens)}</td><td>${formatTokens(m.outputTokens)}</td><td>${formatTokens(m.cacheReadTokens)}</td><td>${formatTokens(m.totalTokens)}</td><td>${formatNumber(m.totalTokensPerSession)}</td><td>${formatNumber(m.totalTokensPerCommit)}</td><td>${formatPercent(m.failedActionRate)}</td></tr>`;
}

function tokenBreakdownRows(breakdown) {
  return Object.entries(breakdown)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, m]) => tokenBreakdownRow(key, m))
    .join('');
}

function renderProviderModel(summary) {
  const header =
    '<thead><tr><th>Key</th><th>Sessions</th><th>Actions</th><th>Input tokens</th><th>Output tokens</th><th>Cache read tokens</th><th>Total tokens</th><th>Tokens/session</th><th>Tokens/commit</th><th>Failed rate</th></tr></thead>';

  const providerRows = KNOWN_PROVIDERS.map((provider) => tokenBreakdownRow(provider, summary.byProvider[provider] ?? emptyMainMetrics())).join('');

  views['provider-model'].innerHTML = `
    <table>
      <caption>By provider (claude-code / copilot / unknown)</caption>
      ${header}
      <tbody>${providerRows}</tbody>
    </table>
    <table>
      <caption>By model</caption>
      ${header}
      <tbody>${tokenBreakdownRows(summary.byModel) || emptyRow(10)}</tbody>
    </table>
  `;
}

function renderAgentSkill(summary, sessions) {
  const header = '<thead><tr><th>Key</th><th>Sessions</th><th>Actions</th><th>Total tokens</th><th>Failed rate</th></tr></thead>';

  const actionsWithAgentOrSkill = sessions.flatMap((session) =>
    session.actions.filter((action) => action.agentUsed || action.skillUsed).map((action) => ({ session, action })),
  );

  const actionCards = actionsWithAgentOrSkill
    .map(
      ({ session, action }) => `
        <article class="session-card">
          <h3>${escapeHtml(session.sessionId)} · ${escapeHtml(action.actionId)}</h3>
          <div class="meta">
            ${action.agentUsed ? `agent: ${escapeHtml(action.agentName ?? 'unknown')}` : ''}
            ${action.agentUsed && action.skillUsed ? ' · ' : ''}
            ${action.skillUsed ? `skill: ${escapeHtml(action.skillName ?? 'unknown')}` : ''}
            · <span class="badge ${statusBadgeClass(action.status)}">${action.status ?? 'pending'}</span>
          </div>
          ${renderResponseBody(action.responseBody)}
        </article>
      `,
    )
    .join('');

  views['agent-skill'].innerHTML = `
    <table>
      <caption>By agent</caption>
      ${header}
      <tbody>${breakdownRows(summary.byAgent) || emptyRow(5)}</tbody>
    </table>
    <table>
      <caption>By skill</caption>
      ${header}
      <tbody>${breakdownRows(summary.bySkill) || emptyRow(5)}</tbody>
    </table>
    <h2>Actions using an agent or skill</h2>
    ${actionCards || '<p class="muted">None yet.</p>'}
  `;
}

function renderNotBuilt(message) {
  statusEl.hidden = true;
  views.overview.hidden = false;
  views.overview.innerHTML = `
    <div class="hint">
      <p>${escapeHtml(message || 'No report has been generated yet.')}</p>
      <p>Run <code>ai-metrics report build</code>, then reload this page.</p>
    </div>
  `;
}

async function main() {
  try {
    const [summaryRes, sessionsRes] = await Promise.all([fetch('/api/summary'), fetch('/api/sessions')]);

    if (summaryRes.status === 404 || sessionsRes.status === 404) {
      const notFoundRes = summaryRes.status === 404 ? summaryRes : sessionsRes;
      const body = await notFoundRes.json().catch(() => ({}));
      renderNotBuilt(body.error);
      return;
    }

    if (!summaryRes.ok || !sessionsRes.ok) {
      throw new Error(`unexpected response (${summaryRes.status}/${sessionsRes.status})`);
    }

    const summary = await summaryRes.json();
    const sessions = await sessionsRes.json();

    statusEl.hidden = true;
    metaEl.textContent = `Generated ${summary.generatedAt} · ${summary.totalEvents} events · ${sessions.length} sessions`;

    renderOverview(summary);
    renderPrompts(sessions);
    renderCommits(summary);
    renderProviderModel(summary);
    renderAgentSkill(summary, sessions);

    for (const [name, el] of Object.entries(views)) {
      el.hidden = name !== 'overview';
    }
  } catch (error) {
    statusEl.hidden = false;
    statusEl.textContent = `Failed to load report: ${error instanceof Error ? error.message : String(error)}`;
    statusEl.classList.add('error');
  }
}

main();
